name: run bot

on:
  push:
  workflow_dispatch:
  schedule:
    #- cron:  '5 1 * * *'
permissions:
  contents: write
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |-
        pip install requests
        # python script.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Latest data" || exit 0
        git diff HEAD^ HEAD | git commit --amend -F -
        git push
